// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.'
  );
}

// Supabase auth storage key — derived from the project ref so it matches what the SDK uses
// Falls back to a generic key if URL is not yet set (e.g. during build)
const projectRef = SUPABASE_URL.match(/https:\/\/([^.]+)\.supabase\.co/)?.[1] ?? 'local';
export const AUTH_STORAGE_KEY = `sb-${projectRef}-auth-token`;

// Debug: log the resolved Supabase URL to help diagnose 404s from PostgREST endpoints
// Remove this in production
try {
  // eslint-disable-next-line no-console
  console.info('[debug] Supabase URL:', SUPABASE_URL);
} catch (e) {
  // ignore
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
  global: {
    headers: {
      'X-Client-Info': 'boundless-health-app',
    },
    fetch: async (url, options = {}) => {
      let lastError: Error | null = null;
      const maxRetries = 3;
      const retryDelay = 1000;

      for (let attempt = 0; attempt < maxRetries; attempt++) {
        try {
          const response = await fetch(url, {
            ...options,
            timeout: 30000,
          } as RequestInit);
          return response;
        } catch (error) {
          lastError = error as Error;
          if (error instanceof TypeError && error.message.includes('Failed to fetch')) {
            if (attempt < maxRetries - 1) {
              await new Promise(resolve => setTimeout(resolve, retryDelay * Math.pow(2, attempt)));
              continue;
            }
          }
          throw error;
        }
      }

      throw lastError || new Error('Network request failed after retries');
    },
  },
});
